# -*- coding: utf-8 -*-
"""bigdata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IaOAWAEuXmtEV86i9HARQ0Y3o2PdLWkR
"""

import pandas as pd

df = pd.read_excel("/content/drive/MyDrive/bigdata/Cópia de serviçosQTD.xlsx")
display(df)

df.describe()

df.iloc[5]

df1 = pd.read_excel("/content/drive/MyDrive/bigdata/Cópia de clientes.xlsx")
display(df1)

df1.describe()

sexo_counts = df1['SEXO'].value_counts()


total_clientes = sexo_counts.sum()


percent_masculino = (sexo_counts['M'] / total_clientes) * 100
percent_feminino = (sexo_counts['F'] / total_clientes) * 100

print(f"Porcentagem de clientes masculinos: {percent_masculino:.2f}%")
print(f"Porcentagem de clientes femininos: {percent_feminino:.2f}%")

df2 = pd.read_excel("/content/drive/MyDrive/bigdata/Cópia de REPOSIÇÃO DE FIOS1.xlsx")
display(df2)

data_bairros_rio = {
    'BAIRRO': [
        'COPACABANA', 'IPANEMA', 'LEBLON', 'BOTAFOGO', 'FLAMENGO', 'TIJUCA',
        'MARACANÃ', 'CENTRO', 'SANTA TERESA', 'LARANJEIRAS', 'RECREIO DOS BANDEIRANTES',
        'BARRA DA TIJUCA', 'JACAREPAGUÁ', 'CAMPO GRANDE', 'BANGU', 'MADUREIRA',
        'MÉIER', 'VILA ISABEL', 'GÁVEA', 'SÃO CONRADO', 'GLÓRIA', 'CATETE',
        'HUMAITÁ', 'LEME', 'URCA', 'COSME VELHO', 'GRAJAÚ', 'PAQUETÁ', 'BONSUCESSO', 'MUZEMA','JARDIM GRAMACHO','MUTUÁ','COMENDADOR SOARES'
    ],
    'ZONA': [
        'ZONA SUL', 'ZONA SUL', 'ZONA SUL', 'ZONA SUL', 'ZONA SUL', 'ZONA NORTE',
        'ZONA NORTE', 'CENTRO', 'CENTRO', 'ZONA SUL', 'ZONA OESTE',
        'ZONA OESTE', 'ZONA OESTE', 'ZONA OESTE', 'ZONA OESTE', 'ZONA NORTE',
        'ZONA NORTE', 'ZONA NORTE', 'ZONA SUL', 'ZONA SUL', 'CENTRO', 'CENTRO',
        'ZONA SUL', 'ZONA SUL', 'ZONA SUL', 'ZONA SUL', 'ZONA NORTE', 'ILHAS', 'ZONA NORTE', 'ZONA OESTE','BAIXADA', 'OUTROS','BAIXADA'
    ]
}

df_bairros_rio = pd.DataFrame(data_bairros_rio)

print(df_bairros_rio)

ClientesBairros = df2[['NOME', 'BAIRRO']]
print(ClientesBairros)

junção_df = pd.merge(ClientesBairros, df_bairros_rio, on='BAIRRO', how='left')

# Exibir o novo DataFrame resultante
print(junção_df)

# Contar o número de ocorrências de cada zona
contagem_zona = junção_df['ZONA'].value_counts()

# Calcular o número total de registros
total_registros = len(junção_df)

# Calcular a porcentagem de cada zona
porcentagem_zona = (contagem_zona / total_registros) * 100

# Exibir a porcentagem de cada zona
display(porcentagem_zona)

# Definir os intervalos de idade para cada categoria
faixas_etarias = {
    'Criança': (0, 12),
    'Adolescente': (12, 18),
    'Jovem': (15, 30),
    'Adulto': (30, 60),
    'Idoso': (60, float('inf'))
}

# Função para determinar a categoria de idade de um cliente
def categorizar_idade(idade):
    for faixa, (limite_inferior, limite_superior) in faixas_etarias.items():
        if limite_inferior <= idade < limite_superior:
            return faixa
    return 'Desconhecido'

# Aplicar a função para categorizar a idade de cada cliente
df2['Faixa Etária'] = df2['IDADE'].apply(categorizar_idade)

# Contar o número de ocorrências em cada faixa etária
contagem_faixas_etarias = df2['Faixa Etária'].value_counts()

# Calcular o número total de clientes
total_clientes = len(df2)

# Calcular a porcentagem de clientes em cada faixa etária
porcentagem_faixas_etarias = (contagem_faixas_etarias / total_clientes) * 100

# Exibir a porcentagem de clientes em cada faixa etária
print(porcentagem_faixas_etarias)

